server:
  port: 9001
spring:
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://172.19.10.40:8026/db_wechat?useUnicode=true&characterEncoding=utf-8&useSSL=false
    username: root
    password: zrSQ7?uwA
    hikari:
      minimum-idle: 5
      idle-timeout: 600000
      maximum-pool-size: 10
      auto-commit: true
      pool-name: MyHikariCP
      max-lifetime: 1800000
      connection-timeout: 30000
      connection-test-query: SELECT 1
mybatis:
  type-aliases-package: com.lzj.my.spring.security.domain
  configuration:
    map-underscore-to-camel-case: true
logging:
  level:
    com.itheima: debug
rsa:
  key:
    pubKeyFile: id_key_rsa.pub
    priKeyFile: id_key_rsa
token:
  expiration: 1440